### ISSUE TITLE
Understanding Different types of Graphs in Graph ML

### ISSUE THREAD

**Issue by Anindyadeep** [patrickloeber/blogposts-pythonengineer#15]
This is the part 2 of this blog post series, I intended to start. Here I will cover the topic `Different types of graphs in Graph ML and understanding different tasks in Graph ML in details, which covers:
1. Attributed Graph
2. Hetero Graph
3. Temporal Graphs
   a. Static Temporal Graphs
   b. Dynamic Temporal Graphs

And different level of tasks in Graph ML, as those are:
1. Node level tasks
2. Link level tasks
3. Graph level tasks

I will be providing complete description of this topic in the next blog.
Thank you.

**Comment by python-engineer** [comment]
Looks good!
